name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python setup.py install
        python setup.py develop
        pip install allure-behave
        pip install behave
        pip install selenium
    - name: Test with behave
      run: |
        python tests/runner.py --test_dir=tests --run_allure=true --behave_options="-k -D browser=headless_chrome"
    - name: Allure generate report 
  # You may pin to the exact commit or the version.
  # uses: yhrunyk/action-allure-generate-report@4989321d11790c05c69750d1bbb3ea374ba06baa
      uses: yhrunyk/action-allure-generate-report@master
      with:
        results-dir: tests/results
    # Allure report target dir
        report-dir: default is allure-report
    
