name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python setup.py install
        python setup.py develop
        pip install allure-behave
        pip install behave
        pip install selenium
    - name: Test with behave
      run: |
        python tests/runner.py --test_dir=tests --run_allure=true --behave_options="-k -D browser=headless_chrome"
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with: 
        ref: master
        path: master

    - name: Allure report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: tests/results
        gh-pages: master
        allure_report: allure-report
        allure_history: allure-history
        
    
